
const descriptions = {
    icamaxi: "ICA is the leading grocery retailer in Sweden, with around 1,300 stores and a market share of around 36%. Shown on the map are not all of the ICA stores, but 'ICA Maxi Stormarknad', which are ICA's largest stores - hypermarkets with a wide range of groceries, as well as non-food items such as housewares, entertainment and garden supplies.",
    ikea: "IKEA designs and sells furniture, kitchen appliances, and home accessories. It's the world's largest furniture retailer with around 450 locations globally.",
    kronans: "Kronans Apotek is a Swedish pharmacy company, and the third largest pharmacy chain in the country. It was founded in 1907 with history going back to the early 18th century.",
    max: "Max Burgers AB is the oldest hamburger resturaunt chain in Sweden. Before the 1990s, most of their locations and popularity was in northern Sweden. Today though, MAX is a nationwide fast-food chain, and so is therir popupality, with For nine consecutive years, Max has had the most satisfied customers among the nationwide fast food chains in Sweden, beating McDonald's and Burger King by large margins.",
    policeStations: "No description",
    powerplants: "Most energy production in Sweden comes from hydro/water power and nuclear power. The energy sources for power plants in Sweden are hydro at 142 power plants, wind: 10, biomass: 8, nuclear: 3, gas: 3, oil: 1, coal: 1.",
    chargingstations: "An EV charging station is a machine that supplies electric energy for the recharging of electric vehicles. The displayed data is not of all charging stations in Sweden, but just those of one of the leading EV charging operators, a company called 'Bee'.",
    oldestcompanies: "Take 'active' with a grain of salt. It just means that they are still active in one way or another. Some of these companies have since being founded been absorbed by other companies and become subsidaries. Others have changed name, location, and even business operations. Is it stil the same company? You decide: https://youtu.be/LAh8HryVaeY",
    districtcourts: "In Sweden, there are three types of general courts: the district courts, the courts of appeal, and the supreme court. The district court (Swedish: tingsrätt) is the first instance you'd come in contact with in a criminal case, civil law dispute, or non-contentious matters. Proceedings in this court are generally open to the public. The second, and next instance after district courts, are the courts of appeal (hovrätt), which deal with appeals against decisions of the district courts. The third and final instance, in a civil or criminal case, is the Supreme Court (Swedish: Högsta domstolen). ",
    prisons: "While every prison serves the same basic purpose, the prisons in Sweden have different classifications of security, from 1 to 3, where 1 is the highest classification and 3 is the lowest.",
}
